# Generated by Django 5.2.5 on 2025-09-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salesdetail_price_unit_alter_sale_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdetail',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='salesdetail',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
